### ISSUE TITLE
Optional features

### ISSUE THREAD

**Issue by Eviato** [padok-team/docs-terraform-guidelines#23]
By reading [this page](https://github.com/padok-team/docs-terraform-guidelines/blob/main/terraform/optional-attributes.md) I've got several questions/remarks

**Reason 1** , with latest Terraform version, it's fixed. Here's a working example:

```hcl
terraform {
  required_version = "1.3.7"

  required_providers {
    random = {
      source = "hashicorp/random"
      version = "3.4.3"
    }
  }
}

provider "random" {}

variable "mappy" {
  description = "Object with optional value"
  type = object({
    name = string
    number = optional(number, 10)
  })

  validation {
    condition = var.mappy.number >= 5
    error_message = "Number of mappy object must be equal or higher than 5."
  }
}

resource "random_pet" "this" {
  prefix = var.mappy.name
  length = var.mappy.number
}
```

You can test it with the following command
```bash
❯ terraform plan -var 'mappy={name="pitchoune",number=5}'

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # random_pet.this will be created
  + resource "random_pet" "this" {
      + id        = (known after apply)
      + length    = 5
      + prefix    = "pitchoune"
      + separator = "-"
    }

Plan: 1 to add, 0 to change, 0 to destroy.

❯ terraform plan -var 'mappy={name="pitchoune",number=4}'
╷
│ Error: Invalid value for variable
│
│   on main.tf line 14:
│   14: variable "mappy" {
│     ├────────────────
│     │ var.mappy.number is 4
│
│ Number of mappy object must be equal or higher than 5.
│
│ This was checked by the validation rule at main.tf:21,3-13.
```

**Reason 2**: In the latest Terraform version ( `>=1.3.0`), `optional` function is no longer consider as experimental and can be used directly without any warning. 

**Reason 3**: I'm totally agree about that reason in the case, the Ops is working on a oldest codebase, but the upgrade can still be made, what's stopping you?

**Comment by Laudenlaruto** [comment]
To answer your concerns :
Reason 1 is not fixed because I think you didn't spot the typo. `procotol` vs `protocol`. Terraform is not capable of finding typos for you except if you have a validation for each parameter, but that defeat the purpose of the optional parameter.
I agree for reason 2 but since not everyone is >=1.3.0 we will keep it for the time being.
And for reason 3 nothing is stopping us apart the fact that it will be harder to upgrade than without it. 

Do you agree?
